version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/app:delegated
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./etc/php/Dockerfile
    restart: unless-stopped
    ports:
      - "9090:9001"
    volumes:
      - ./src:/app:delegated